CREATE TABLE USER (
	id INTEGER NOT NULL,
  	name VARCHAR(100),
  	email VARCHAR(50),
  	password VARCHAR(20),
  	PRIMARY KEY (id)
);

CREATE TABLE PHONE (
	id INTEGER NOT NULL,
	id_user INTEGER NOT NULL,
	number VARCHAR(15),
    ddd VARCHAR(5),
    PRIMARY KEY (id),
    FOREIGN KEY (id_user) REFERENCES USER (id)
);